### ISSUE TITLE
other social logins?

### ISSUE THREAD

**Issue by Rainer-Lang** [JhonatasMartins/social-login#2]
Do you plan to integrate also Twitter and/or LinkedIn?
Maybe also something own like "email"+"password"?

**Comment by JhonatasMartins** [comment]
I intend integrate with Twitter maybe with linkedin.
About login with email + password I was thinking about something with no passwords like [digits ](http://get.digits.com) but it is just an idea.

**Comment by Rainer-Lang** [comment]
I need name+pw to make a new account.

BUT digits sounds really good! :-)
Do you have any experience with it?

**Comment by Rainer-Lang** [comment]
Twitter and LinkedIn:
https://github.com/alotagle/SocialLogin-Android/blob/master/app/src/main/java/com/sevenseconds/loginsocial/LoginActivity.java

**Comment by JhonatasMartins** [comment]
No, I don't have experience with digits but it sounds easy to implement
and nice link I will take a look

**Comment by Rainer-Lang** [comment]
I'm looking forward to the integration of digits. It sounds really great!

**Comment by Rainer-Lang** [comment]
A friend of mine integrated digits in an iOS app - and it's working fine.
